name: flutter_secure_storage
description: Secure Storage plugin for Flutter.
version: 2.0.0
author: German Saprykin <saprykin.h@gmail.com>
homepage: https://github.com/mogol/flutter_secure_storage

flutter:
  plugin:
    androidPackage: com.it_nomads.fluttersecurestorage
    pluginClass: FlutterSecureStoragePlugin

dependencies:
  flutter:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <3.0.0"